name: KGZ Mobile Force Old Gradle

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Клонирование репозитория
      uses: actions/checkout@v4

    - name: 2. Распаковка архива
      run: unzip -o project.zip

    - name: 3. Настройка Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 4. Принудительная установка Gradle 7.4.2
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '7.4.2'

    - name: 5. Сборка Лаунчера
      run: |
        cd launcher
        gradle assembleDebug --no-daemon

    - name: 6. Сборка Клиента
      run: |
        cd android
        gradle assembleDebug --no-daemon || echo "Клиент пока пропускаем"

    - name: 7. Сохранение готовых APK
      uses: actions/upload-artifact@v4
      with:
        name: kgz-mobile-apks
        path: '**/*.apk'
